
const Discord = require('discord.js');
const Twana1 = new Discord.Client();
const Twana2 = new Discord.Client();
const Twana3 = new Discord.Client();
const Twana4 = new Discord.Client();
const Twana5 = new Discord.Client();
const Twana6 = new Discord.Client();
const Twana7 = new Discord.Client();
const Twana8 = new Discord.Client();
const Twana9 = new Discord.Client();
const Twana10 = new Discord.Client();
const Twana11 = new Discord.Client();
const Twana12 = new Discord.Client();
const Twana13 = new Discord.Client();
const Twana14 = new Discord.Client();
const Twana15 = new Discord.Client();
const Twana16 = new Discord.Client();
const Twana17 = new Discord.Client();
const Twana18 = new Discord.Client();
const Twana19 = new Discord.Client();
const Twana20 = new Discord.Client();
const Twana21 = new Discord.Client();
const Twana22 = new Discord.Client();
const Twana23 = new Discord.Client();
const Twana24 = new Discord.Client();
const Twana25 = new Discord.Client();
const Twana26 = new Discord.Client();
const Twana27 = new Discord.Client();
const Twana28 = new Discord.Client();
const Twana29 = new Discord.Client();
const Twana30 = new Discord.Client();
const Twana31 = new Discord.Client();
const Twana32 = new Discord.Client();
const Twana33 = new Discord.Client();
const Twana34 = new Discord.Client();
const Twana35 = new Discord.Client();
const Twana36 = new Discord.Client();
const Twana37 = new Discord.Client();
const Twana38 = new Discord.Client();
const Twana39 = new Discord.Client();
const Twana40 = new Discord.Client();
const Twana41 = new Discord.Client();
const Twana42 = new Discord.Client();
const Twana43 = new Discord.Client();
const Twana44 = new Discord.Client();
const Twana45 = new Discord.Client();
const Twana46 = new Discord.Client();
const Twana47 = new Discord.Client();
const Twana48 = new Discord.Client();
const Twana49 = new Discord.Client();
const Twana50 = new Discord.Client();
const Twana51 = new Discord.Client();
const Twana52 = new Discord.Client();
const Twana53 = new Discord.Client();
const Twana54 = new Discord.Client();
const Twana55 = new Discord.Client();
const Twana56 = new Discord.Client();
const Twana57 = new Discord.Client();
const Twana58 = new Discord.Client();
const Twana59 = new Discord.Client();
const Twana60 = new Discord.Client();
const Twana61 = new Discord.Client();
const Twana62 = new Discord.Client();
const Twana63 = new Discord.Client();
const Twana64 = new Discord.Client();
const Twana65 = new Discord.Client();
const Twana66 = new Discord.Client();
const Twana67 = new Discord.Client();
const Twana68 = new Discord.Client();
const Twana69 = new Discord.Client();
const Twana70 = new Discord.Client();
const Twana71 = new Discord.Client();
const Twana72 = new Discord.Client();
const Twana73 = new Discord.Client();
const Twana74 = new Discord.Client();
const Twana75 = new Discord.Client();
const Twana76 = new Discord.Client();
const Twana77 = new Discord.Client();
const Twana78 = new Discord.Client();
const Twana79 = new Discord.Client();
const Twana80 = new Discord.Client();
const Twana81 = new Discord.Client();
const Twana82 = new Discord.Client();
const Twana83 = new Discord.Client();
const Twana84 = new Discord.Client();
const Twana85 = new Discord.Client();
const Twana86 = new Discord.Client();
const Twana87 = new Discord.Client();
const Twana88 = new Discord.Client();
const Twana89 = new Discord.Client();
const Twana90 = new Discord.Client();
const Twana91 = new Discord.Client();
const Twana92 = new Discord.Client();
const Twana93 = new Discord.Client();
const Twana94 = new Discord.Client();
const Twana95 = new Discord.Client();
const Twana96 = new Discord.Client();
const Twana97 = new Discord.Client();
const Twana98 = new Discord.Client();
const Twana99 = new Discord.Client();
const Twana100= new Discord.Client();



Twana1.login("ODEzOTI2NTc3OTMwNjMzMjM2.YDWa4Q.PPub-v0PF4JdNHm2K9O5qDHS3h8");
Twana2.login("ODEzOTI3Mjg3NjgxOTc0Mjcy.YDWhRQ.tQ9TS-m5jQ3kfhIwCRWTZzXkOaQ");
Twana3.login("ODEzOTMzNTY5NDkwODEyOTcw.YDWhXQ.exY7P4w90tXq4fuy7Vf6QsMlsoA");
Twana4.login("ODEzOTM0MTM2MzA5ODQxOTcy.YDWh8g.jE2zdjQ3wNHgp-9T4KBbezFPaMU");
Twana5.login("ODEzOTM0ODgwMjc4MDUyOTE2.YDWidw.RhETri-XriQf7e-GH7xNVpJyIG8");
Twana6.login("ODEzOTM1NDM5OTgyNzU1ODgw.YDWjJw.FDZ3qo92Dt4rXwPHabD3z5l8PGc");
Twana7.login("ODEzOTM2MTcxNjU0MzE2MDkz.YDWjrA.nx75ET6hfBJdCpWmAoQ3tREMLDc");
Twana8.login("ODA3NTgzMzU4NTIzMTQ2Mjgw.YB6Hvg.2UN2gKwBTGFFKcnbje-2f8wF14E");
Twana9.login("ODA3NTg0Njg4NTIwNTYwNzAw.YB6ImA.KsyJTRX9gw574aT1kLeY5nssy_U");
Twana10.login("ODA3NTg1NTQ5NTgxMTU2MzUy.YB6JTg.Z4qkG3dREM1Jq4-oAi_oQn6jiBQ");
Twana11.login("ODA3NTg2MzQ3NDE3NjAwMDEw.YB6Kqw.LMYbQCFbkwABF-rikbsK0kP7rt0");
Twana12.login("ODA3NTg4OTM5MDUzMDA2ODg3.YB6NGA.erENf8VBJSd--UnCJ35ecwVVKPU");
Twana13.login("ODA3NTkyMTYxMDIwNDc3NDYx.YB6PSw.pPVlm5DYPShjhgRLhx9iyMK3XlQ");
Twana14.login("ODA3NTkzMzQyMDk4ODY2MTc2.YB6QVg.TB_O0RyNwnE3XXduLkGCdvdlZnY");
Twana15.login("ODEzOTM2NzMxOTg3Mzc4MjE2.YDWkPg.aIsisGotzIapNP14CyZnA5vWZt0");
Twana16.login("ODEzOTM3MzA3MzU4OTg2Mjgx.YDWklQ.qnmn_noAJ6o8qTY6DarhRFFjzcM");
Twana17.login("ODEzOTM4MDEzMTQ2NDQ3OTIy.YDYh3g.fhXxW1D1dyciJvez96NLgxmvLgg");
Twana18.login("ODE0MDcyMTgzMjQ0MDYyNzYw.YDYiew.Rr2MQNHPPzKlgCOSFv4ErbyXnJo");
Twana19.login("ODE0MDcyODkwMDYzNTg1MzUw.YDYjBA.TN5VIMteVG6qugk3JtFhJVpKOcM");
Twana20.login("ODE0MDczNDcwMDQzNDIyNzMw.YDYjhA.-qzwUqi8Lj0zdxiPbrMfxdVPtzw");
Twana21.login("ODE0MDc0MDAzMDAxMTgwMTgx.YDYj8w.J7BgsQQ1LURJqWFlcuEsDxRYpEY");
Twana22.login("ODE0MDc0NDc0MzgyMDk4NDMy.YDYkaQ._l4C3VZnZCiCBVq4_x4Ddk2AyLE");
Twana23.login("ODE0MDc0OTY2NjEzNTU3Mjg4.YDYk9A.ONEsFPKpPzrsF3O6cbfburQiEeY");
Twana24.login("ODE0MDc1NTQ1NjYxNzM0OTMy.YDYlYA.9VOckvNnUNqjYgXRCJAwksLQ15A");
Twana25.login("ODE0MDc2MDAxODA1OTI2NDQy.YDYl2Q.DAXiVHUimUm0NfdAZ8IDMz-Bh_M");
Twana26.login("ODE0MDc2NTEwMjkzMTk2ODMw.YDYmYA.FR3MeIc7nMvqrIr67djjjt_N1nA");
Twana27.login("");
Twana28.login("");
Twana29.login("");
Twana30.login("");
Twana31.login("");
Twana32.login("");
Twana33.login("");
Twana34.login("");
Twana35.login("");
Twana36.login("");
Twana37.login("");
Twana38.login("");
Twana39.login("");
Twana40.login("");
Twana41.login("");
Twana42.login("");
Twana43.login("");
Twana44.login("");
Twana45.login("");
Twana46.login("");
Twana47.login("");
Twana48.login("");
Twana49.login("");
Twana50.login("");
Twana51.login("");
Twana52.login("");
Twana53.login("");
Twana54.login("");
Twana55.login("");
Twana56.login("");
Twana57.login("");
Twana58.login("");
Twana59.login("");
Twana60.login("");
Twana61.login("");
Twana62.login("");
Twana63.login("");
Twana64.login("");
Twana65.login("");
Twana66.login("");
Twana67.login("");
Twana68.login("");
Twana69.login("");
Twana70.login("");
Twana71.login("");
Twana72.login("");
Twana73.login("");
Twana74.login("");
Twana75.login("");
Twana76.login("");
Twana77.login("");
Twana78.login("");
Twana79.login("");
Twana80.login("");
Twana81.login("");
Twana82.login("");
Twana83.login("");
Twana84.login("");
Twana85.login("");
Twana86.login("");
Twana87.login("");
Twana88.login("");
Twana89.login("");
Twana90.login("");
Twana91.login("");
Twana92.login("");
Twana94.login("");
Twana95.login("");
Twana96.login("");
Twana97.login("");
Twana98.login("");
Twana99.login("");
Twana100.login("");









